# Generated by Django 2.2.2 on 2019-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
