# Generated by Django 2.2.2 on 2019-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_remove_entry_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
